### ISSUE TITLE
Won't install in VSCode

### ISSUE THREAD

**Issue by robinmattern** [triforcely/CollapseLevel#5]
When I used the command "Install from VSIX ..." in VSCode, nothing gets installed, nothing happens.  When I use the Windows CMD window to run this command: 

    `code --install-extension .\Installs\VSCode\Extensions\CollapseLevel.vsix`

I get the error below.  Would you just have to create a package.json file, or would it be more complicated than that?  

    Error: extension/package.json not found inside zip.
    at ZipFile.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\cliProcessMain.js:118:142)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at ZipFile.emit (events.js:188:7)
    at FdSlicer.<anonymous> (C:\Program Files\Microsoft VS Code\resources\app\node_modules\yauzl\index.js:198:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at FdSlicer.emit (events.js:188:7)
    at onCloseDone (C:\Program Files\Microsoft VS Code\resources\app\node_modules\fd-slicer\index.js:74:12)
    at FSReqWrap.oncomplete (fs.js:114:15)

**Comment by triforcely** [comment]
Hi Robin. This extension is for "Visual Studio", not "Visual Studio Code".
